export default {
  light: {
    text: '#1C1C1C',
    subtext: "#999999",
    background: '#EEEEEE',
    tint: '#00BEC4',
    tabIconDefault: '#999999',
    tabIconSelected: '#00BEC4',
    dollars: '#00BEC4',
    activeSessionsPayments: "#00BEC4",
    inactiveSessionsPayments: "#1C1C1C",
    activeMembersTrainers: "#00BEC4",
    inactiveMembersTrainers: "#1C1C1C",
    changesSaved: "#1C1C1C",
    firstName: "#1C1C1C",
    lastName: "#999999",
    goodsessions: "#1C1C1C",
    badsessions: "#00BEC4",
    switchbackground: '#C1C1C1',
    login: "#00BEC4",
    signup: "#AA00DC",
    loginRegisterForgotPass: "#00BEC4"
  },
  dark: {
    text: '#FFFFFF',
    subtext: "#999999",
    background: '#1C1C1C',
    tint: '#FFFFFF',
    tabIconDefault: '#C1C1C1',
    tabIconSelected: '#FFFFFF',
    dollars: '#72FA41',
    activeSessionsPayments: "#FFFFFF",
    inactiveSessionsPayments: "#EEEEEE",
    activeMembersTrainers: "#FFFFFF",
    inactiveMembersTrainers: "#EEEEEE",
    changesSaved: "#72FA41",
    firstName: "#FFFFFF",
    lastName: "#C1C1C1",
    goodsessions: "#FFFFFF",
    badsessions: "#00BEC4",
    switchbackground: '#999999',
    login: "#00BEC4",
    signup: "#AA00DC",
    loginRegisterForgotPass: "#C1C1C1"
  },
};
